name: ChunkAnalysis
main: com.mcmiddleearth.chunkanalysis.ChunkAnalysis
version: 1.1
description: Analysis or modification of chunks in the world
author: Dallen, Eriol_Eandur
depend: [WorldEdit]
softdepend: [MCME-Architect, ResourceRegions]
commands:
  block:
    description: analyse of modify blocks by filter
    usage: |
            /block analyse <Block ID>[:data] -t [json tags] -p [pack] -s
            /block replace <Find ID>[:find data] -t [find tags] <Replace ID>[:replace data] -t [replace tags] -s -p [pack] -d